import { Mission } from '@/app/page';

export const ALL_TASKS: Mission[] = [
  // SAC (8 tasks)
  { id: 'sac-1', category: 'SAC', type: 'chat', company: 'Netflix', title: 'Moderador de Conteúdo - Netflix Content Ops', value: 18.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'sac-2', category: 'SAC', type: 'chat', company: 'Amazon', title: 'Analista de Suporte Tier 1 - Amazon AWS', value: 22.50, logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'sac-3', category: 'SAC', type: 'chat', company: 'Shopee', title: 'Revisor de Disputas - Shopee Trust', value: 15.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Shopee.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'sac-4', category: 'SAC', type: 'chat', company: 'Mercado Livre', title: 'Auditor de Fraude - Meli Compliance', value: 25.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/MercadoLivre.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'sac-5', category: 'SAC', type: 'chat', company: 'Uber', title: 'Especialista em Segurança - Uber Safety', value: 20.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'sac-6', category: 'SAC', type: 'chat', company: 'Ifood', title: 'Analista de Qualidade - iFood Ops', value: 17.50, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Ifood_logo.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'sac-7', category: 'SAC', type: 'chat', company: 'Apple', title: 'Support Specialist - Apple Care+', value: 35.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg', completed: false, level: 4, currency: 'USD', duration: '5 min' },
  { id: 'sac-8', category: 'SAC', type: 'chat', company: 'Spotify', title: 'Content Reviewer - Spotify Trust', value: 28.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Spotify_logo_with_text.svg', completed: false, level: 4, currency: 'EUR', duration: '5 min' },

  // IA (8 tasks)
  { id: 'ia-1', category: 'IA', type: 'logic', company: 'OpenAI', title: 'Avaliador de IA Generativa - OpenAI Data Team', value: 12.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/OpenAI_Logo.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'ia-2', category: 'IA', type: 'logic', company: 'Google', title: 'Auditor de Qualidade de Busca - Google Search Ops', value: 14.50, logo: 'https://upload.wikimedia.org/wikipedia/commons/2/2f/Google_2015_logo.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'ia-3', category: 'IA', type: 'image', company: 'Meta', title: 'Moderador de Conteúdo - Meta Trust & Safety', value: 28.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Meta_Platforms_Inc._logo.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'ia-4', category: 'IA', type: 'input', company: 'Microsoft', title: 'Analista de Dados - Microsoft AI', value: 24.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Microsoft_logo_%282012%29.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'ia-5', category: 'IA', type: 'logic', company: 'Anthropic', title: 'Revisor de Ética em IA - Anthropic Safety', value: 19.50, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/14/Anthropic_logo.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'ia-6', category: 'IA', type: 'image', company: 'Tesla', title: 'Anotador de Visão Computacional - Tesla Autopilot', value: 32.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg', completed: false, level: 3, currency: 'BRL', duration: '5 min' },
  { id: 'ia-7', category: 'IA', type: 'logic', company: 'Scale AI', title: 'Data Labeling Specialist - Scale AI', value: 45.00, logo: 'https://picsum.photos/seed/scale/100/100', completed: false, level: 4, currency: 'USD', duration: '5 min' },
  { id: 'ia-8', category: 'IA', type: 'input', company: 'DeepMind', title: 'AI Training Specialist - DeepMind Health', value: 55.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/DeepMind_logo.svg', completed: false, level: 4, currency: 'EUR', duration: '5 min' },

  // Logística (8 tasks)
  { id: 'log-1', category: 'Logística', type: 'logic', company: 'Correios', title: 'Auditor de Roteirização - Correios Log', value: 15.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/9/91/Logo_Correios.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'log-2', category: 'Logística', type: 'input', company: 'Loggi', title: 'Analista de Triagem - Loggi Ops', value: 13.50, logo: 'https://upload.wikimedia.org/wikipedia/commons/4/46/Loggi_logo.png', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'log-3', category: 'Logística', type: 'image', company: 'FedEx', title: 'Revisor de Declarações - FedEx Customs', value: 21.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/9/9d/FedEx_Express.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'log-4', category: 'Logística', type: 'logic', company: 'DHL', title: 'Especialista em Classificação - DHL Supply Chain', value: 18.50, logo: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/DHL_Logo.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'log-5', category: 'Logística', type: 'input', company: 'Jadlog', title: 'Auditor de Rastreio - Jadlog Tracking', value: 16.00, logo: 'https://picsum.photos/seed/jadlog/100/100', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'log-6', category: 'Logística', type: 'logic', company: 'Mercado Envios', title: 'Analista de Malha Logística - Meli Envios', value: 26.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/MercadoLivre.svg', completed: false, level: 3, currency: 'BRL', duration: '5 min' },
  { id: 'log-7', category: 'Logística', type: 'logic', company: 'Amazon', title: 'Route Optimization Analyst - Amazon Logistics', value: 38.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg', completed: false, level: 4, currency: 'USD', duration: '5 min' },
  { id: 'log-8', category: 'Logística', type: 'image', company: 'UPS', title: 'Customs Declaration Specialist - UPS', value: 42.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/1b/UPS_logo.svg', completed: false, level: 4, currency: 'USD', duration: '5 min' },

  // QA (8 tasks)
  { id: 'qa-1', category: 'QA', type: 'qa', company: 'Nubank', title: 'Auditor de Interface - Nubank Design Team', value: 25.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Nubank_logo_2021.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'qa-2', category: 'QA', type: 'qa', company: 'PicPay', title: 'Analista de Usabilidade - PicPay UX', value: 22.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/PicPay_Logotipo.png', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'qa-3', category: 'QA', type: 'logic', company: 'Itaú', title: 'Revisor de Transações - Itaú Compliance', value: 30.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/c/c0/Itau_logo.png', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'qa-4', category: 'QA', type: 'qa', company: 'Banco Inter', title: 'Especialista em QA - Inter App', value: 28.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/18/Banco_Inter_logo.png', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'qa-5', category: 'QA', type: 'input', company: 'C6 Bank', title: 'Analista de Bug Bounty - C6 Security', value: 24.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/5/52/C6_Bank_logo.png', completed: false, level: 3, currency: 'BRL', duration: '5 min' },
  { id: 'qa-6', category: 'QA', type: 'logic', company: 'XP Inc', title: 'Auditor de Stress Test - XP Investimentos', value: 35.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/2/25/XP_Inc._logo.png', completed: false, level: 3, currency: 'BRL', duration: '5 min' },
  { id: 'qa-7', category: 'QA', type: 'qa', company: 'Stripe', title: 'UI Testing Specialist - Stripe Checkout', value: 50.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg', completed: false, level: 4, currency: 'USD', duration: '5 min' },
  { id: 'qa-8', category: 'QA', type: 'logic', company: 'Revolut', title: 'Payment Gateway Auditor - Revolut', value: 48.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Revolut_logo.svg', completed: false, level: 4, currency: 'EUR', duration: '5 min' },

  // Tradução / Dados (8 tasks)
  { id: 'td-1', category: 'Tradução', type: 'input', company: 'Duolingo', title: 'Especialista em Localização - Duolingo', value: 16.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/1/15/Duolingo_logo.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'td-2', category: 'Dados', type: 'logic', company: 'IBGE', title: 'Analista de Dados Demográficos - IBGE', value: 14.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/8/87/Logo_IBGE.svg', completed: false, level: 1, currency: 'BRL', duration: '5 min' },
  { id: 'td-3', category: 'Tradução', type: 'input', company: 'Netflix', title: 'Revisor de Legendas Sênior - Netflix', value: 26.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'td-4', category: 'Dados', type: 'input', company: 'Serasa', title: 'Auditor de Dados Cadastrais - Serasa', value: 18.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/8/82/Serasa_Experian_logo.svg', completed: false, level: 2, currency: 'BRL', duration: '5 min' },
  { id: 'td-5', category: 'Tradução', type: 'logic', company: 'Babbel', title: 'Avaliador de Pronúncia - Babbel', value: 22.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Babbel_logo.svg', completed: false, level: 3, currency: 'BRL', duration: '5 min' },
  { id: 'td-6', category: 'Dados', type: 'image', company: 'Receita Federal', title: 'Auditor Fiscal Digital - Receita Federal', value: 29.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/3/36/Receita_Federal_do_Brasil.svg', completed: false, level: 3, currency: 'BRL', duration: '5 min' },
  { id: 'td-7', category: 'Tradução', type: 'input', company: 'Airbnb', title: 'Listing Localization Expert - Airbnb', value: 40.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg', completed: false, level: 4, currency: 'USD', duration: '5 min' },
  { id: 'td-8', category: 'Dados', type: 'logic', company: 'Bloomberg', title: 'Financial Data Auditor - Bloomberg', value: 55.00, logo: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Bloomberg_logo.svg', completed: false, level: 4, currency: 'USD', duration: '5 min' },
];
